# Generated by Django 3.1.3 on 2020-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_name', models.CharField(max_length=20, verbose_name='硬件名称')),
                ('hp_model', models.CharField(max_length=10, verbose_name='硬件型号')),
                ('hp_num', models.IntegerField(verbose_name='数量')),
                ('hp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（万）')),
                ('hp_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价（万）')),
                ('hp_second', models.CharField(max_length=10, verbose_name='二次使用')),
                ('hp_second_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='二次使用价格（万）')),
                ('hp_boss_one', models.CharField(max_length=10, verbose_name='推荐供应商1')),
                ('hp_boss_two', models.CharField(max_length=10, verbose_name='推荐供应商2')),
                ('hp_boss_three', models.CharField(max_length=10, verbose_name='推荐供应商3')),
            ],
            options={
                'verbose_name': '硬件产品',
                'verbose_name_plural': '硬件产品',
                'db_table': 'df_hardware_product',
            },
        ),
        migrations.CreateModel(
            name='SoftwareProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=20, verbose_name='软件名称')),
                ('sp_content', models.CharField(max_length=10, verbose_name='主要内容')),
                ('sp_num', models.IntegerField(verbose_name='数量')),
                ('sp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（万）')),
                ('sp_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价（万）')),
                ('sp_second', models.CharField(max_length=10, verbose_name='二次使用')),
                ('sp_second_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='二次使用价格（万）')),
                ('sp_boss_one', models.CharField(max_length=10, verbose_name='推荐供应商1')),
                ('sp_boss_two', models.CharField(max_length=10, verbose_name='推荐供应商2')),
                ('sp_boss_three', models.CharField(max_length=10, verbose_name='推荐供应商3')),
            ],
            options={
                'verbose_name': '软件产品',
                'verbose_name_plural': '软件产品',
                'db_table': 'df_software_product',
            },
        ),
    ]
